title: Advanced Quantitative Economics with Python
author: Thomas J. Sargent & John Stachurski
logo: _static/qe-logo-large.png

execute:
  execute_notebooks: "cache"
  timeout: 1200
#   run_in_temp: true

bibtex_bibfiles:
   - _static/quant-econ.bib

sphinx:
  extra_extensions: [sphinx_multitoc_numbering]
  config:
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
      jupyter:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    mathjax_config:
      TeX:
        Macros:
          "argmax" : "arg\\,max"
          "argmin" : "arg\\,min"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
